version: '3'

volumes:
  tipster-postgres-data:
    driver: local

services:
  postgres:
    image: postgres:11
    container_name: elixir_kids
    volumes:
      - tipster-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres